# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  paymentservice:
    image: paymentservice
    build:
      context: .
      dockerfile: PaymentService/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5165:5165
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
