apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
      - name: paymentservice
        image: lpsantos/paymentservice:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5165
