apiVersion: v1
kind: Service
metadata: 
  name: paymentservice
spec:
  selector:
    app: paymentservice
  type: NodePort
  ports:
  - protocol: TCP
    nodePort: 30005
    port: 5165
    targetPort: 5165
