apiVersion: v1
kind: Service
metadata: 
  name: productservice
spec:
  selector:
    app: productservice
  type: NodePort
  ports:
  - protocol: TCP
    nodePort: 30007
    port: 5167
    targetPort: 5167
