apiVersion: v1
kind: Service
metadata: 
  name: shoppingcartservice
spec:
  selector:
    app: shoppingcartservice
  type: NodePort
  ports:
  - protocol: TCP
    nodePort: 30009
    port: 5169
    targetPort: 5169
